### ISSUE TITLE
Can't build a project with the extension

### ISSUE THREAD

**Issue by flure** [defold/extension-admob#1]
Every time I try building my project with extension-admob, I get this error message :
`Build failed: Resource 'dirtylarry/button.gui' is not created`

With that stacktrace :

```
com.dynamo.bob.CompileExceptionError: Resource 'dirtylarry/button.gui' is not created
	at com.dynamo.bob.Project.build(Project.java:343)
	at com.dynamo.cr.editor.builders.ContentBuilder.buildLocal(ContentBuilder.java:135)
	at com.dynamo.cr.editor.builders.ContentBuilder.build(ContentBuilder.java:81)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:321)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:396)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:618)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
	at org.eclipse.core.internal.resources.Project.build(Project.java:124)
	at com.dynamo.cr.editor.handlers.LaunchHandler$1.run(LaunchHandler.java:153)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException: Resource 'dirtylarry/button.gui' is not created
	at com.dynamo.bob.fs.DefaultFileSystem.calcSha1(DefaultFileSystem.java:46)
	at com.dynamo.bob.fs.DefaultFileSystem.sha1(DefaultFileSystem.java:67)
	at com.dynamo.bob.fs.DefaultResource.sha1(DefaultResource.java:75)
	at com.dynamo.bob.Task.calculateSignature(Task.java:120)
	at com.dynamo.bob.Project.runTasks(Project.java:844)
	at com.dynamo.bob.Project.doBuild(Project.java:728)
	at com.dynamo.bob.Project.build(Project.java:335)
	... 13 more
```

**Comment by mathiaswking** [comment]
Hi @flure!
If you try the menu option "Project -> Fetch Libraries", does that help?

**Comment by flure** [comment]
I just tried it, it doesn't solve the problem.
Maybe it is because I'm trying to run it directly on my Android device, through dmengine ?

**Comment by mathiaswking** [comment]
But you see the "dirtylarry" folder to your left in the editor right?
And, after that, you choose "Project -> Bundle -> Android application..." ?

"Maybe it is because I'm trying to run it directly on my Android device, through dmengine ?"
Well, your error log is from the build (what platform did you build for?), so that's before running the dmengine.

**Comment by flure** [comment]
My bad. It seems I've pasted some example code without checking if I had all the resources.
Sorry for wasting your time... :(
