### ISSUE TITLE
NonSdkApiUsedViolation after upload to Google Play

### ISSUE THREAD

**Issue by Rudiz-osd** [defold/extension-admob#11]
Banner works without any issues before uploading release package to Google Play.

Stack trace from Pre-launch report:

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->address:J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.internal.ads.zzewd.zzC(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzewd.zzB(com.google.android.gms:play-services-ads@@20.1.0:3)
	at com.google.android.gms.internal.ads.zzewd.<clinit>(com.google.android.gms:play-services-ads@@20.1.0:34)
	at com.google.android.gms.internal.ads.zzewd.zzq(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzeur.<clinit>(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzeur.zzl(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzeug.zza(com.google.android.gms:play-services-ads@@20.1.0:10)
	at com.google.android.gms.internal.ads.zzeuw.zzb(com.google.android.gms:play-services-ads@@20.1.0:3)
	at com.google.android.gms.internal.ads.zzetd.zzag(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzetd.zzah(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzclp.zzb(com.google.android.gms:play-services-ads@@20.1.0:7)
	at com.google.android.gms.internal.ads.zzeyk.zzb(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzcmt.zza(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzcma.zzb(com.google.android.gms:play-services-ads@@20.1.0:3)
	at com.google.android.gms.internal.ads.zzeyk.zzb(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzeyu.zzc(com.google.android.gms:play-services-ads@@20.1.0:4)
	at com.google.android.gms.internal.ads.zzdvh.zza(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzdvg.zzb(com.google.android.gms:play-services-ads@@20.1.0:3)
	at com.google.android.gms.internal.ads.zzeyk.zzb(com.google.android.gms:play-services-ads@@20.1.0:1)
	at com.google.android.gms.internal.ads.zzbju.zzb(com.google.android.gms:play-services-ads@@20.1.0:5)
	at com.google.android.gms.internal.ads.zzdna.zza(com.google.android.gms:play-services-ads@@20.1.0:43)
	at com.google.android.gms.internal.ads.zzdci.zzN(com.google.android.gms:play-services-ads@@20.1.0:4)
	at com.google.android.gms.internal.ads.zzdci.zze(com.google.android.gms:play-services-ads@@20.1.0:2)
	at com.google.android.gms.internal.ads.zzacs.zzg(com.google.android.gms:play-services-ads-lite@@20.1.0:22)
	at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@20.1.0:1)
	at com.defold.admob.AdmobJNI$7.run(AdmobJNI.java:450)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Rudiz-osd** [comment]
**Update**.
Did some testing and uploading. Today Google Play provides this answer to the issue:

_"This issue may be associated with Google- supplied library Protocol Buffers. We know about this issue, and we are working on it. There is nothing you need to do at the moment"_

However, I still have this pointed out from the Pre-launch test:

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at aLZ.a(PG:11)
	at aMw.a(PG:11)
	at aMa.a(PG:43)
	at cBg.<init>(PG:4)
	at cAx.run(PG:9)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by britzl** [comment]
> StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z

This also seems like a very generic warning that I doubt is within our control.

**Comment by Rudiz-osd** [comment]
> > StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z
> 
> This also seems like a very generic warning that I doubt is within our control.

Yeah. I'm actually gonna close this issue
