### ISSUE TITLE
Reward Video Android Problem

### ISSUE THREAD

**Issue by Bipex** [defold/extension-admob#4]
I have an exception when a video finished

10-07 21:12:50.164 19219-19219/? D/DynamitePackage: Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl
10-07 21:12:59.580 19219-19219/? W/Ads: Invoke Firebase method getCurrentScreenClass error.
                                        java.lang.NoSuchMethodException: getCurrentScreenClass []
                                            at java.lang.Class.getMethod(Class.java:1981)
                                            at java.lang.Class.getDeclaredMethod(Class.java:1960)
                                            at com.google.android.gms.ads.internal.scionintegration.b.f(:com.google.android.gms.DynamiteModulesA@11517440:125)
                                            at com.google.android.gms.ads.internal.scionintegration.b.f(:com.google.android.gms.DynamiteModulesA@11517440:32)
                                            at com.google.android.gms.ads.internal.al.M(:com.google.android.gms.DynamiteModulesA@11517440:103)
                                            at com.google.android.gms.ads.internal.client.bp.a(:com.google.android.gms.DynamiteModulesA@11517440:10)
                                            at com.google.ads.mediation.AbstractAdViewAdapter.showVideo(:com.google.android.gms.DynamiteModulesA@11517440:228)
                                            at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA@11517440:193)
                                            at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA@11517440:29)
                                            at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA@11517440:11)
                                            at android.os.Binder.transact(Binder.java:507)
                                            at com.google.android.gms.internal.zznr$zza$zza.show(Unknown Source)
                                            at com.google.android.gms.internal.zznz.show(Unknown Source)
                                            at com.google.firebase.admob.internal.cpp.RewardedVideoHelper$3.run(RewardedVideoHelper.java:190)
                                            at android.os.Handler.handleCallback(Handler.java:751)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:154)
                                            at android.app.ActivityThread.main(ActivityThread.java:6682)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
10-07 21:12:59.582 19219-19219/? W/Ads: Invoke Firebase method getCurrentScreenName error.
                                        java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
                                            at com.google.android.gms.ads.internal.scionintegration.b.f(:com.google.android.gms.DynamiteModulesA@11517440:33)
                                            at com.google.android.gms.ads.internal.al.M(:com.google.android.gms.DynamiteModulesA@11517440:103)
                                            at com.google.android.gms.ads.internal.client.bp.a(:com.google.android.gms.DynamiteModulesA@11517440:10)
                                            at com.google.ads.mediation.AbstractAdViewAdapter.showVideo(:com.google.android.gms.DynamiteModulesA@11517440:228)
                                            at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA@11517440:193)
                                            at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA@11517440:29)
                                            at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA@11517440:11)
                                            at android.os.Binder.transact(Binder.java:507)
                                            at com.google.android.gms.internal.zznr$zza$zza.show(Unknown Source)
                                            at com.google.android.gms.internal.zznz.show(Unknown Source)
                                            at com.google.firebase.admob.internal.cpp.RewardedVideoHelper$3.run(RewardedVideoHelper.java:190)
                                            at android.os.Handler.handleCallback(Handler.java:751)
                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                            at android.os.Looper.loop(Looper.java:154)
                                            at android.app.ActivityThread.main(ActivityThread.java:6682)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
10-07 21:13:13.188 19425-19425/? A/DEBUG:     #03 pc 000b2f18  /data/app/com.defold.bipex.laser-1/lib/arm/liblaser_game.so (_ZN14AdMobExtension18QueueRewardCommandEiifPKc+64)
10-07 21:13:13.188 19425-19425/? A/DEBUG:     #04 pc 000b5cfc  /data/app/com.defold.bipex.laser-1/lib/arm/liblaser_game.so (_ZN14AdMobExtension21RewardedVideoListener10OnRewardedEN8firebase5admob14rewarded_video10RewardItemE+64)
10-07 21:13:13.188 19425-19425/? A/DEBUG:     #05 pc 000c10d9  /data/app/com.defold.bipex.laser-1/lib/arm/liblaser_game.so (_ZN8firebase5admob14rewarded_video8internal21RewardedVideoInternal22NotifyListenerOfRewardENS1_10RewardItemE+136)
10-07 21:13:13.188 19425-19425/? A/DEBUG:     #06 pc 000be033  /data/app/com.defold.bipex.laser-1/lib/arm/liblaser_game.so (Java_com_google_firebase_admob_internal_cpp_RewardedVideoHelper_grantReward+326)
10-07 21:13:47.128 19467-19467/? D/DynamitePackage: Instantiating com.google.android.gms.ads.reward.ChimeraRewardedVideoAdCreatorImpl

Thinks

**Comment by AGulev** [comment]
[New implementation of AdMob SDK from scratch released](https://github.com/defold/extension-admob/releases/tag/2.0.0)
